import type { DailyWeather } from "@/domain/thermal/diurnal";
import type { LngLat } from "@/domain/shared/geo";

/**
 * Perfis que guiam a geração dos dados DEMONSTRATIVOS.
 * Nomes de bairros são reais; posições, malha de quarteirões, logradouros secundários
 * e indicadores são SINTÉTICOS e aproximados (ver docs/DATA.md).
 */

export type NeighborhoodKind =
  "centro" | "misto" | "residencial-medio" | "residencial-alto" | "periferia" | "industrial";

export interface NeighborhoodProfile {
  name: string;
  kind: NeighborhoodKind;
  /** Deslocamento do centro do bairro em relação ao centro do município (km leste, km norte). */
  offsetKm: readonly [east: number, north: number];
  radiusKm: number;
  /** Propensão ao calor (0–1): materiais, adensamento, atividade industrial. */
  heat: number;
  canopy: number;
  incomePerCapita: number;
  elderlyShare: number;
  densityPerKm2: number;
  /** Multiplicador de circulação de pedestres. */
  pedestrian: number;
  streets: readonly string[];
}

export interface MunicipalityProfile {
  municipalityId: string;
  codePrefix: string;
  center: LngLat;
  /** Traçado aproximado do Rio Paraíba do Sul na área urbana. */
  river: readonly LngLat[];
  weather: DailyWeather;
  neighborhoods: readonly NeighborhoodProfile[];
}

const GENERIC_STREETS = [
  "Rua Sete de Setembro",
  "Rua Tiradentes",
  "Rua São João",
  "Rua Duque de Caxias",
  "Rua Santos Dumont",
  "Rua Rio Branco",
  "Rua das Acácias",
  "Rua Santa Rita",
  "Rua Dom Pedro II",
  "Rua Marechal Deodoro",
  "Rua Benjamin Constant",
  "Rua dos Ipês",
  "Rua Princesa Isabel",
  "Rua Minas Gerais",
  "Rua Espírito Santo",
  "Rua das Palmeiras",
  "Rua Quinze de Novembro",
  "Rua Castro Alves",
  "Rua das Margaridas",
  "Rua Rui Barbosa",
] as const;

/** Mistura logradouros característicos do bairro com nomes genéricos, de forma estável. */
function streets(primary: readonly string[], offset: number): string[] {
  const generic = GENERIC_STREETS.map(
    (_, i) => GENERIC_STREETS[(i + offset) % GENERIC_STREETS.length],
  );
  return [...primary, ...generic.slice(0, Math.max(0, 7 - primary.length))];
}

/** Dia quente típico de verão (no piloto: estação INMET de referência). */
const summerDay = (
  municipalityId: string,
  tMin: number,
  tMax: number,
  stationName: string,
): DailyWeather => ({
  municipalityId,
  date: "2026-01-20",
  stationName,
  tMin,
  tMax,
  rhAtMin: 0.82,
  windMean: 1.6,
  solarPeak: 900,
});

export const MUNICIPALITY_PROFILES: readonly MunicipalityProfile[] = [
  {
    municipalityId: "volta-redonda",
    codePrefix: "VR",
    center: [-44.104, -22.5231],
    river: [
      [-44.175, -22.535],
      [-44.15, -22.52],
      [-44.125, -22.508],
      [-44.1, -22.503],
      [-44.075, -22.507],
      [-44.05, -22.495],
      [-44.03, -22.49],
    ],
    weather: summerDay("volta-redonda", 22.8, 35.4, "Volta Redonda (referência demonstrativa)"),
    neighborhoods: [
      {
        name: "Vila Santa Cecília",
        kind: "centro",
        offsetKm: [0, 0],
        radiusKm: 0.6,
        heat: 0.85,
        canopy: 0.08,
        incomePerCapita: 2600,
        elderlyShare: 0.19,
        densityPerKm2: 8500,
        pedestrian: 1,
        streets: streets(["Av. Amaral Peixoto", "Rua 33", "Rua 14", "Rua 16", "Rua 20"], 0),
      },
      {
        name: "Área Industrial",
        kind: "industrial",
        offsetKm: [-2, 0.3],
        radiusKm: 0.65,
        heat: 1,
        canopy: 0.04,
        incomePerCapita: 1800,
        elderlyShare: 0.1,
        densityPerKm2: 400,
        pedestrian: 0.3,
        streets: streets(["Av. dos Trabalhadores", "Rua da Siderurgia", "Rua do Aço"], 3),
      },
      {
        name: "Aterrado",
        kind: "misto",
        offsetKm: [0.9, 3.05],
        radiusKm: 0.5,
        heat: 0.7,
        canopy: 0.12,
        incomePerCapita: 2900,
        elderlyShare: 0.2,
        densityPerKm2: 9500,
        pedestrian: 0.75,
        streets: streets(["Av. Paulo de Frontin"], 5),
      },
      {
        name: "Niterói",
        kind: "periferia",
        offsetKm: [3.6, 3],
        radiusKm: 0.5,
        heat: 0.75,
        canopy: 0.07,
        incomePerCapita: 1100,
        elderlyShare: 0.12,
        densityPerKm2: 11000,
        pedestrian: 0.5,
        streets: streets([], 7),
      },
      {
        name: "Retiro",
        kind: "periferia",
        offsetKm: [-3, -1.4],
        radiusKm: 0.55,
        heat: 0.8,
        canopy: 0.06,
        incomePerCapita: 1050,
        elderlyShare: 0.11,
        densityPerKm2: 12500,
        pedestrian: 0.6,
        streets: streets(["Av. Sávio Gama"], 9),
      },
      {
        name: "Santo Agostinho",
        kind: "periferia",
        offsetKm: [-1.4, -2.8],
        radiusKm: 0.45,
        heat: 0.7,
        canopy: 0.09,
        incomePerCapita: 980,
        elderlyShare: 0.1,
        densityPerKm2: 10500,
        pedestrian: 0.4,
        streets: streets([], 11),
      },
      {
        name: "Conforto",
        kind: "residencial-medio",
        offsetKm: [1.5, -1.7],
        radiusKm: 0.5,
        heat: 0.55,
        canopy: 0.14,
        incomePerCapita: 1900,
        elderlyShare: 0.16,
        densityPerKm2: 7500,
        pedestrian: 0.45,
        streets: streets([], 13),
      },
      {
        name: "Jardim Amália",
        kind: "residencial-alto",
        offsetKm: [2.8, -0.4],
        radiusKm: 0.45,
        heat: 0.35,
        canopy: 0.24,
        incomePerCapita: 3900,
        elderlyShare: 0.21,
        densityPerKm2: 5200,
        pedestrian: 0.35,
        streets: streets([], 15),
      },
      {
        name: "Laranjal",
        kind: "residencial-alto",
        offsetKm: [1.3, 0.9],
        radiusKm: 0.4,
        heat: 0.4,
        canopy: 0.26,
        incomePerCapita: 4300,
        elderlyShare: 0.23,
        densityPerKm2: 4800,
        pedestrian: 0.35,
        streets: streets([], 17),
      },
      {
        name: "Belmonte",
        kind: "periferia",
        offsetKm: [-3.4, 2],
        radiusKm: 0.45,
        heat: 0.65,
        canopy: 0.1,
        incomePerCapita: 1150,
        elderlyShare: 0.12,
        densityPerKm2: 9000,
        pedestrian: 0.4,
        streets: streets([], 19),
      },
    ],
  },
  {
    municipalityId: "barra-mansa",
    codePrefix: "BM",
    center: [-44.1714, -22.544],
    river: [
      [-44.24, -22.555],
      [-44.205, -22.548],
      [-44.18, -22.54],
      [-44.16, -22.537],
      [-44.13, -22.528],
      [-44.11, -22.52],
    ],
    weather: summerDay("barra-mansa", 23.2, 36, "Volta Redonda (referência demonstrativa)"),
    neighborhoods: [
      {
        name: "Centro",
        kind: "centro",
        offsetKm: [0, -0.6],
        radiusKm: 0.5,
        heat: 0.85,
        canopy: 0.07,
        incomePerCapita: 2300,
        elderlyShare: 0.2,
        densityPerKm2: 8000,
        pedestrian: 0.95,
        streets: streets(["Av. Joaquim Leite", "Rua Pinto Ribeiro"], 2),
      },
      {
        name: "Ano Bom",
        kind: "misto",
        offsetKm: [-0.9, 1.6],
        radiusKm: 0.45,
        heat: 0.65,
        canopy: 0.1,
        incomePerCapita: 1700,
        elderlyShare: 0.17,
        densityPerKm2: 8500,
        pedestrian: 0.55,
        streets: streets(["Av. Domingos Mariano"], 4),
      },
      {
        name: "Vista Alegre",
        kind: "periferia",
        offsetKm: [1.3, -1.9],
        radiusKm: 0.45,
        heat: 0.75,
        canopy: 0.07,
        incomePerCapita: 1000,
        elderlyShare: 0.11,
        densityPerKm2: 11000,
        pedestrian: 0.45,
        streets: streets([], 6),
      },
      {
        name: "Saudade",
        kind: "residencial-medio",
        offsetKm: [-1.6, -1.6],
        radiusKm: 0.45,
        heat: 0.6,
        canopy: 0.12,
        incomePerCapita: 1600,
        elderlyShare: 0.16,
        densityPerKm2: 8000,
        pedestrian: 0.4,
        streets: streets([], 8),
      },
      {
        name: "Área Industrial",
        kind: "industrial",
        offsetKm: [-3.4, -1.6],
        radiusKm: 0.6,
        heat: 1,
        canopy: 0.04,
        incomePerCapita: 1500,
        elderlyShare: 0.1,
        densityPerKm2: 300,
        pedestrian: 0.25,
        streets: streets(["Rua da Metalurgia"], 10),
      },
      {
        name: "Boa Sorte",
        kind: "periferia",
        offsetKm: [1.6, 2.3],
        radiusKm: 0.45,
        heat: 0.7,
        canopy: 0.08,
        incomePerCapita: 980,
        elderlyShare: 0.1,
        densityPerKm2: 10500,
        pedestrian: 0.4,
        streets: streets([], 12),
      },
      {
        name: "Colônia Santo Antônio",
        kind: "periferia",
        offsetKm: [-2.4, -3.3],
        radiusKm: 0.45,
        heat: 0.7,
        canopy: 0.1,
        incomePerCapita: 950,
        elderlyShare: 0.09,
        densityPerKm2: 9000,
        pedestrian: 0.35,
        streets: streets([], 14),
      },
      {
        name: "Jardim Boa Vista",
        kind: "residencial-alto",
        offsetKm: [2.6, -0.4],
        radiusKm: 0.4,
        heat: 0.4,
        canopy: 0.22,
        incomePerCapita: 3400,
        elderlyShare: 0.2,
        densityPerKm2: 5000,
        pedestrian: 0.3,
        streets: streets([], 16),
      },
    ],
  },
  {
    municipalityId: "resende",
    codePrefix: "RS",
    center: [-44.4467, -22.4689],
    river: [
      [-44.51, -22.48],
      [-44.48, -22.47],
      [-44.455, -22.461],
      [-44.43, -22.455],
      [-44.4, -22.448],
      [-44.38, -22.445],
    ],
    weather: summerDay("resende", 21, 34.2, "Resende (referência demonstrativa)"),
    neighborhoods: [
      {
        name: "Centro",
        kind: "centro",
        offsetKm: [0, -0.4],
        radiusKm: 0.5,
        heat: 0.8,
        canopy: 0.1,
        incomePerCapita: 2500,
        elderlyShare: 0.19,
        densityPerKm2: 7000,
        pedestrian: 0.85,
        streets: streets([], 1),
      },
      {
        name: "Campos Elíseos",
        kind: "misto",
        offsetKm: [1.8, 2.6],
        radiusKm: 0.55,
        heat: 0.65,
        canopy: 0.12,
        incomePerCapita: 2700,
        elderlyShare: 0.17,
        densityPerKm2: 8000,
        pedestrian: 0.75,
        streets: streets(["Av. Albino de Almeida"], 3),
      },
      {
        name: "Jardim Jalisco",
        kind: "residencial-medio",
        offsetKm: [-1.8, -1],
        radiusKm: 0.45,
        heat: 0.55,
        canopy: 0.14,
        incomePerCapita: 2100,
        elderlyShare: 0.15,
        densityPerKm2: 6500,
        pedestrian: 0.4,
        streets: streets([], 5),
      },
      {
        name: "Manejo",
        kind: "residencial-medio",
        offsetKm: [2, -1],
        radiusKm: 0.45,
        heat: 0.55,
        canopy: 0.16,
        incomePerCapita: 2200,
        elderlyShare: 0.16,
        densityPerKm2: 6000,
        pedestrian: 0.35,
        streets: streets([], 7),
      },
      {
        name: "Paraíso",
        kind: "periferia",
        offsetKm: [-1.3, 1.9],
        radiusKm: 0.45,
        heat: 0.7,
        canopy: 0.09,
        incomePerCapita: 1150,
        elderlyShare: 0.11,
        densityPerKm2: 9000,
        pedestrian: 0.4,
        streets: streets([], 9),
      },
      {
        name: "Cidade Alegria",
        kind: "periferia",
        offsetKm: [-3.3, 1.4],
        radiusKm: 0.45,
        heat: 0.75,
        canopy: 0.07,
        incomePerCapita: 950,
        elderlyShare: 0.09,
        densityPerKm2: 10500,
        pedestrian: 0.45,
        streets: streets([], 11),
      },
      {
        name: "Vicentina",
        kind: "periferia",
        offsetKm: [-0.8, -2.4],
        radiusKm: 0.4,
        heat: 0.65,
        canopy: 0.1,
        incomePerCapita: 1100,
        elderlyShare: 0.12,
        densityPerKm2: 8500,
        pedestrian: 0.35,
        streets: streets([], 13),
      },
      {
        name: "Morada da Colina",
        kind: "residencial-alto",
        offsetKm: [0.9, -2.6],
        radiusKm: 0.45,
        heat: 0.3,
        canopy: 0.3,
        incomePerCapita: 4600,
        elderlyShare: 0.2,
        densityPerKm2: 3800,
        pedestrian: 0.25,
        streets: streets([], 15),
      },
      {
        name: "Distrito Industrial",
        kind: "industrial",
        offsetKm: [4.4, 3.6],
        radiusKm: 0.6,
        heat: 0.95,
        canopy: 0.05,
        incomePerCapita: 1600,
        elderlyShare: 0.1,
        densityPerKm2: 300,
        pedestrian: 0.25,
        streets: streets(["Rodovia do Polo Industrial"], 17),
      },
    ],
  },
];
